refactor: reconfiguring the role

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,117 +1,63 @@
-name: 'Terraform Infrastructure Provisioning'
+name: Terraform Infrastructure Provisioning
 
-on: workflow_dispatch
+on:
+  pull_request:
+    branches:
+      - main            # Trigger a workflow that target the main branch
+      - staging  
+      - '!dev'
+      - '!feature/*'
+      # - 'releases/**'
+
 
 permissions:
   contents: read
   id-token: write
 
 jobs:
-  terraform:
-    name: 'Terraform'
+  Infra_provisioning:
     runs-on: ubuntu-latest
-    environment: production
+    #environment: staging
     defaults:
       run:
         shell: bash
-        working-directory: ./terraform
-
+        working-directory: ./infra
     steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Configure AWS Credentials
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
-        aws-region: us-east-1
+      - name: Checkout code
+        uses: actions/checkout@v4
     
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Configure AWS Credentials for Development Environment
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: us-east-1
+          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
+                         
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3
 
-    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
-
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-    - name: Terraform Init
-      run: terraform init
+      - name: Terraform Init
+        run: terraform init
 
     # Checks that all Terraform configuration files adhere to a canonical format
-    - name: Terraform Format
-      run: terraform fmt -check
+      - name: Terraform Format
+        run: terraform fmt -check
 
     # Generates an execution plan for Terraform
-    - name: Terraform Plan
-      run: terraform plan -input=false
+      - name: Terraform Plan
+        run: terraform plan -input=false
 
     # Apply the Configuration
-    - name: Terraform Apply
-      run: terraform apply -input=false -auto-approve
+      - name: Terraform Apply
+        run: terraform apply -input=false -auto-approve
 
-
-# name: Terraform Infrastructure Provisioning
-
-# on:
-#   pull_request:
-#     branches:
-#       - main            # Trigger a workflow that target the main branch
-#       - staging  
-#       - '!dev'
-#       - '!feature/*'
-#       # - 'releases/**'
-
-
-# permissions:
-#   contents: read
-#   id-token: write
-
-# jobs:
-#   Infra_provisioning:
-#     runs-on: ubuntu-latest
-#     #environment: staging
-#     defaults:
-#       run:
-#         shell: bash
-#         working-directory: ./infra
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v4
-    
-#       - name: Configure AWS Credentials for Development Environment
-#         uses: aws-actions/configure-aws-credentials@v4
-#         with:
-#           # role-to-assume: ${{ secrets.AWS_PUBLIC_KEY }}
-#           # aws-region: us-east-1
-#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
-#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
-#           aws-region: us-east-1
-#           role-to-assume: arn:aws:iam::681117582889:role/oidc-setup-gitops2024Role-NBBinsf7DC2S
-                         
-#       - name: Set up Terraform
-#         uses: hashicorp/setup-terraform@v3
-
-#       - name: Terraform Init
-#         run: terraform init
-
-#     # Checks that all Terraform configuration files adhere to a canonical format
-#       - name: Terraform Format
-#         run: terraform fmt -check
-
-#     # Generates an execution plan for Terraform
-#       - name: Terraform Plan
-#         run: terraform plan -input=false
-
-#     # Apply the Configuration
-#       - name: Terraform Apply
-#         run: terraform apply -input=false -auto-approve
-
-#       - name: Check Terraform Status
-#         run: |
-#           if [ $? -ne 0 ]; then
-#             echo "Terraform apply failed"
-#             exit 1
-#           else
-#             echo "Terraform apply succeeded"
-#           fi
+      - name: Check Terraform Status
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Terraform apply failed"
+            exit 1
+          else
+            echo "Terraform apply succeeded"
+          fi
 
 
 
